version: "3.1"

recipe: default.v1

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
  - name: FallbackClassifier
    threshold: 0.6
    ambiguity_threshold: 0.1
    fallback_intent_name: "fallback_semantic"  # 👈 key setting


policies:
- name: RulePolicy
  core_fallback_threshold: 0.6
  core_fallback_action_name: "action_semantic_faq"
assistant_id: 20250520-174200-endothermic-platform
